### Get Users count
GET http://localhost:8080/api/count/users


### Get Authors count
GET http://localhost:8080/api/count/authors

### Get Posts count
GET http://localhost:8080/api/count/posts


### Get all Users
GET http://localhost:8080/api/users/


### Get all Users query ids
GET http://localhost:8080/api/users/?order_by=username&order_type=desc&filter_by=id&filter_by_op=in&filter_by_val=(1,3)

### Get all Users query username like
GET http://localhost:8080/api/users/?order_by=username&order_type=desc&filter_by=username&filter_by_op=like&filter_by_val='%25as%25'


### Get User by id
GET http://localhost:8080/api/users/2


### Create new User
POST http://localhost:8080/api/users/
Content-Type: application/json

{
    "full_name": "alex",
    "username": "alex",
    "password": "test",
    "is_admin": true
}

### Update new User
PUT http://localhost:8080/api/users/1
Content-Type: application/json

{
    "full_name": "full_name",
    "username": "test",
    "password": "test",
    "is_admin": false
}
