### Get Users count
GET http://localhost:8080/api/count/users


### Get all Users
GET http://localhost:8080/api/users/

### Get User by id
GET http://localhost:8080/api/users/2


### Create new User
POST http://localhost:8080/api/users/
Content-Type: application/json

{
    "full_name": "full_name",
    "username": "test",
    "password": "test",
    "is_admin": true
}

### Update new User
PUT http://localhost:8080/api/users/1
Content-Type: application/json

{
    "full_name": "full_name",
    "username": "test",
    "password": "test",
    "is_admin": false
}
