## Users API ###################################################################

### Get Users count
GET http://localhost:8080/api/count/users


### Get all Users
GET http://localhost:8080/api/schema/users/


### Get all Users
GET http://localhost:8080/api/users/?order_by=username&order_type=asc


### Get all Users query ids
GET http://localhost:8080/api/users/?order_by=username&order_type=desc&filter_by=id&filter_by_op=in&filter_by_val=(1,3)


### Get all Users query username like
GET http://localhost:8080/api/users/?order_by=username&order_type=desc&filter_by=username&filter_by_op=like&filter_by_val='%25as%25'


### Get User by id
GET http://localhost:8080/api/users/2


### Create new User
POST http://localhost:8080/api/users/
Content-Type: application/json

{
    "full_name": "galina",
    "username": "galina",
    "password": "test",
    "is_admin": true
}


### Update new User
PUT http://localhost:8080/api/users/1
Content-Type: application/json

{
    "full_name": "Alex Bez",
    "username": "alex",
    "password": "test",
    "email": "alex@email.com",
    "is_admin": true
}


## Images API  ###################################################################


### Get Images count
GET http://localhost:8080/api/count/images


### Create new Image
POST http://localhost:8080/api/images
Content-Type: application/json

{
    "url": "https://vlang.io/img/veasel.png",
    "title": "vlang veasel"
}


### Get Image by id
GET http://localhost:8080/api/images/1


### Update Image by id
PUT http://localhost:8080/api/images/1
Content-Type: application/json

{
    "url": "https://vlang.io/img/veasel.png",
    "title": "vlang veasel - updated"
}

### Get all Images
GET http://localhost:8080/api/images/?order_by=title&order_type=desc


## Posts API  ###################################################################


### Get Posts count
GET http://localhost:8080/api/count/posts


### Create new Post
POST http://localhost:8080/api/posts/
Content-Type: application/json

{
    "title": "test post",
    "body": "test post body",
    "top_image_id": 1
}

### Get Post by id
GET http://localhost:8080/api/posts/1


### Update Post by id
PUT http://localhost:8080/api/posts/1
Content-Type: application/json

{
    "title": "test post - updated",
    "body": "test post body",
    "top_image_id": 1
}

### Get all Posts
GET http://localhost:8080/api/posts/?order_by=title&order_type=desc